version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_app
    container_name: laravel_app_container
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    networks:
      - n-laravel
    depends_on:
      - db
    env_file:
      - .env
    command: sh -c "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=80"

  db:
    image: postgres:13
    container_name: postgres_container
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - n-laravel
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  redis:
    image: redis:7
    container_name: redis_container
    restart: unless-stopped
    networks:
      - n-laravel
    ports:
      - "6379:6379"

volumes:
  postgres_data:

networks:
  n-laravel:
    driver: bridge